use_frameworks!

platform :ios, '10.0'

target 'CloudMessagingAdmin' do
  pod 'CloudInAppMessaging', :path => '../'
end

target 'TestApp' do
  pod 'CloudInAppMessaging', :path => '../'
end

target 'CloudInAppMessaging_Tests' do
  pod 'OCMock'
end

# Fixes indexing error: "Could not build module 'Foundation'"
# https://stackoverflow.com/questions/25999754/could-not-build-module-foundation
# This setting affects only build / indexing process.
#
post_install do |installer_representation|
  installer_representation.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['CLANG_ENABLE_MODULES'] = 'NO'
    end
  end
end
