use_frameworks!

platform :ios, '8.0'

target 'CloudInAppMessaging_Example' do
  pod 'CloudInAppMessaging', :path => '../'

  target 'CloudInAppMessaging_Tests' do
    inherit! :search_paths

    
  end
end
