use_frameworks!
platform :ios, '11.0'

target 'CloudInAppMessaging_Example' do
  pod 'CloudInAppMessaging', :path => '../'

  target 'CloudInAppMessaging_Tests' do
    inherit! :search_paths
    
    pod 'CloudInAppMessaging', :path => '../'
  end
  
end


# Fixes indexing error: "Could not build module 'Foundation'"
# https://stackoverflow.com/questions/25999754/could-not-build-module-foundation
# This setting affects only build / indexing process.
#
post_install do |installer_representation|
  installer_representation.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['CLANG_ENABLE_MODULES'] = 'NO'
    end
  end
end
